### ISSUE TITLE
How to use icon in sidebar?

### ISSUE THREAD

**Issue by SuperManito** [homotechsual/docusaurus.community#7]
Can you provide a detailed tutorial? I am new to use react. Thank you so much

More convenient to use in components than using MDXComponents

Creat file **src/components/Icon/index.ts**
```
import React from 'react'
import { Icon } from '@iconify/react'

export function ICON ({ children }: { children: string }) {
  return (
    <span>
        <Icon icon={children} height="24" style={{verticalAlign: "-0.35em"}}></Icon>
    </span>
  )
}
```

Use in markdown
```
import { ICON } from '@site/src/components/Icon';
<ICON>mdi:github</ICON>
```

**Comment by homotechsual** [comment]
No, I cannot provide detailed tutorial, I'm happy to answer specific questions - customising Docusaurus requires some knowledge of React and JS - that's unavoidable.
